# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Neko_without_frame_command.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1384, 581)
        MainWindow.setMinimumSize(QtCore.QSize(216, 0))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setStyleSheet("opacity: 0;\n"
                                 "")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(360, 139, 731, 471))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame_main)
        self.label.setGeometry(QtCore.QRect(360, -80, 721, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("material/Без имени-1 2 (1).png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_main)
        self.label_3.setGeometry(QtCore.QRect(0, 290, 491, 91))
        self.label_3.setStyleSheet("font-size: 18px;\n"
                                   "line-height: 40px;\n"
                                   "\n"
                                   "color: #FFFFFF;\n"
                                   "background: rgba(23, 23, 23, 0.85);\n"
                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "border-radius: 13px;")
        self.label_3.setObjectName("label_3")
        self.setting_frame = QtWidgets.QFrame(self.frame_main)
        self.setting_frame.setGeometry(QtCore.QRect(0, 80, 283, 179))
        self.setting_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                         "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                         "border-radius: 13px;")
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        self.scrollArea = QtWidgets.QScrollArea(self.setting_frame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, -1, 281, 181))
        self.scrollArea.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                      "border-radius: 13px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 181))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 30, 200, 32))
        self.pushButton_3.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.rule_command_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.rule_command_button.setGeometry(QtCore.QRect(40, 80, 200, 32))
        self.rule_command_button.setStyleSheet("border-radius: 2px;\n"
                                               "font: 12pt \"MS Shell Dlg 2\";\n"
                                               "color: rgba(255, 255, 255, 0.67);\n"
                                               "\n"
                                               "background: rgba(23, 23, 23, 0.31);\n"
                                               "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                               "box-sizing: border-box;\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.rule_command_button.setObjectName("rule_command_button")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 130, 200, 32))
        self.pushButton_7.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setGeometry(QtCore.QRect(-6, 0, 61, 61))
        self.pushButton_11.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                         "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                         "border-radius: 13px;")
        self.pushButton_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("material/image 42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_5 = QtWidgets.QFrame(self.frame_main)
        self.frame_5.setGeometry(QtCore.QRect(170, 140, 571, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_main)
        self.frame_2.setGeometry(QtCore.QRect(580, 90, 91, 217))
        self.frame_2.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(14, 10, 61, 61))
        self.pushButton.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("material/image 40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.like_command_button = QtWidgets.QPushButton(self.frame_2)
        self.like_command_button.setEnabled(True)
        self.like_command_button.setGeometry(QtCore.QRect(14, 76, 61, 61))
        self.like_command_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                               "border-radius: 13px;")
        self.like_command_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("material/image 41.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.like_command_button.setIcon(icon2)
        self.like_command_button.setIconSize(QtCore.QSize(50, 50))
        self.like_command_button.setAutoDefault(False)
        self.like_command_button.setDefault(False)
        self.like_command_button.setObjectName("like_command_button")
        self.teg_button = QtWidgets.QPushButton(self.frame_2)
        self.teg_button.setEnabled(True)
        self.teg_button.setGeometry(QtCore.QRect(14, 136, 61, 61))
        self.teg_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;")
        self.teg_button.setText("")
        self.teg_button.setIcon(icon)
        self.teg_button.setIconSize(QtCore.QSize(50, 50))
        self.teg_button.setAutoDefault(False)
        self.teg_button.setDefault(False)
        self.teg_button.setObjectName("teg_button")
        self.frame_rule_command = QtWidgets.QFrame(self.centralwidget)
        self.frame_rule_command.setGeometry(QtCore.QRect(19, 19, 1361, 561))
        self.frame_rule_command.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rule_command.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rule_command.setObjectName("frame_rule_command")

        # фрейм где отображается выбор кнопок для удаления
        self.frame_8 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_8.setGeometry(QtCore.QRect(270, 480, 661, 81))
        self.frame_8.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "border-radius: 13px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_8)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 7, 641, 71))
        self.scrollArea_3.setStyleSheet(" QScrollBar:horizontal {\n"
                                        "    border: none;\n"
                                        "    background: rgb(23, 23, 23);\n"
                                        "    border-radius: 10px;\n"
                                        "\n"
                                        "    hight: 5px;\n"
                                        "    margin: 8px -20px 0px -30px;\n"
                                        "    \n"
                                        " }\n"
                                        "\n"
                                        "/*  HANDLE BAR VERTICAL */\n"
                                        "QScrollBar::handle:horizontal {    \n"
                                        "    background-color: rgba(255, 255, 255, 0.67);\n"
                                        "    max-height: 4px;\n"
                                        "    max-width: 10px;\n"
                                        "    border-radius: 10px;\n"
                                        "\n"
                                        "}\n"
                                        "/* BTN TOP - SCROLLBAR */\n"
                                        "QScrollBar::sub-line:horizontal {\n"
                                        "    border: none;\n"
                                        "    \n"
                                        "    width:0 px;\n"
                                        "    border-top-left-radius: 7px;\n"
                                        "    border-top-right-radius: 7px;\n"
                                        "    subcontrol-position: left;\n"
                                        "    subcontrol-origin: margin;\n"
                                        "}\n"
                                        "/* RESET ARROW */\n"
                                        "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
                                        "    background: none;\n"
                                        "}\n"
                                        "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
                                        "    background: none;\n"
                                        "}\n"
                                        "")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_2")
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1218, 54))
        self.scrollAreaWidgetContents_3.setStyleSheet("background: rgba(23, 23, 23, 0.0);")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")


        # self.pushButton_17 = QtWidgets.QPushButton(self.frame_8)
        # self.pushButton_17.setGeometry(QtCore.QRect(30, 20, 200, 32))
        # self.pushButton_17.setStyleSheet("border-radius: 2px;\n"
        #                                  "font: 12pt \"MS Shell Dlg 2\";\n"
        #                                  "color: rgba(255, 255, 255, 0.67);\n"
        #                                  "\n"
        #                                  "background: rgba(23, 23, 23, 0.31);\n"
        #                                  "border: 1px solid rgba(233, 233, 233, 0.22);\n"
        #                                  "box-sizing: border-box;\n"
        #                                  "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        # self.pushButton_17.setObjectName("pushButton_17")
        # self.pushButton_18 = QtWidgets.QPushButton(self.frame_8)
        # self.pushButton_18.setGeometry(QtCore.QRect(240, 20, 200, 32))
        # self.pushButton_18.setStyleSheet("border-radius: 2px;\n"
        #                                  "font: 12pt \"MS Shell Dlg 2\";\n"
        #                                  "color: rgba(255, 255, 255, 0.67);\n"
        #                                  "\n"
        #                                  "background: rgba(23, 23, 23, 0.31);\n"
        #                                  "border: 1px solid rgba(233, 233, 233, 0.22);\n"
        #                                  "box-sizing: border-box;\n"
        #                                  "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        # self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_rule_command)
        self.pushButton_19.setGeometry(QtCore.QRect(940, 480, 71, 61))
        self.pushButton_19.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                         "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                         "border-radius: 13px;\n"
                                         "font-size: 18px;\n"
                                         "line-height: 27px;\n"
                                         "\n"
                                         "color: #FFFFFF;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_rule_command)
        self.lineEdit_2.setGeometry(QtCore.QRect(480, 380, 405, 55))
        self.lineEdit_2.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 37px;\n"
                                      "\n"
                                      "color: rgba(255, 255, 255, 0.67);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_rule_command)
        self.pushButton_20.setGeometry(QtCore.QRect(890, 380, 46, 55))
        self.pushButton_20.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                         "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                         "border-radius: 13px;\n"
                                         "font-size: 18px;\n"
                                         "line-height: 27px;\n"
                                         "\n"
                                         "color: #FFFFFF;")
        self.pushButton_20.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("material/image 32.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_20.setIcon(icon3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.frame_9 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_9.setGeometry(QtCore.QRect(510, 250, 348, 87))
        self.frame_9.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "border-radius: 13px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 331, 81))
        self.label_5.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                   "font-size: 14px;\n"
                                   "line-height: 24px;\n"
                                   "\n"
                                   "color: #FFFFFF;")
        self.label_5.setObjectName("label_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_10.setGeometry(QtCore.QRect(510, 130, 348, 87))
        self.frame_10.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                    "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                    "border-radius: 13px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 348, 91))
        self.label_4.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                   "font-size: 14px;\n"
                                   "line-height: 24px;\n"
                                   "\n"
                                   "color: #FFFFFF;")
        self.label_4.setObjectName("label_4")
        self.bread_button = QtWidgets.QPushButton(self.frame_rule_command)
        self.bread_button.setGeometry(QtCore.QRect(300, 100, 191, 131))
        self.bread_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                        "border-radius: 13px;\n"
                                        "font-size: 18px;\n"
                                        "line-height: 27px;\n"
                                        "\n"
                                        "color: #FFFFFF;")
        self.bread_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("material/image 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bread_button.setIcon(icon4)
        self.bread_button.setIconSize(QtCore.QSize(260, 146))
        self.bread_button.setObjectName("bread_button")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_rule_command)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 270, 151, 55))
        self.lineEdit_4.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 37px;\n"
                                      "\n"
                                      "color: rgba(255, 255, 255, 0.67);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.frame_rule_command)
        self.label_8.setGeometry(QtCore.QRect(900, 100, 201, 251))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("material/Без имени-1 2.png"))
        self.label_8.setObjectName("label_8")
        self.rule_command_back_button = QtWidgets.QPushButton(self.frame_rule_command)
        self.rule_command_back_button.setGeometry(QtCore.QRect(950, 380, 81, 51))
        self.rule_command_back_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                                    "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                                    "border-radius: 13px;\n"
                                                    "font-size: 18px;\n"
                                                    "line-height: 27px;\n"
                                                    "\n"
                                                    "color: #FFFFFF;")
        self.rule_command_back_button.setObjectName("rule_command_back_button")
        self.frame_11 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_11.setGeometry(QtCore.QRect(10, 79, 281, 311))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")

        # сетка для отображения выбранных файлов
        # self.grid = QtWidgets.QGridLayout(self.frame_11)
        # self.label_9 = QtWidgets.QLabel(self.frame_11)
        # self.label_9.setGeometry(QtCore.QRect(170, 10, 121, 151))
        # self.label_9.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
        #                            "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
        #                            "border-radius: 13px;\n"
        #                            "font-size: 12px;\n"
        #                            "line-height: 27px;\n"
        #                            "\n"
        #                            "color: #FFFFFF;")
        # self.label_9.setObjectName("")
        # self.label_9.hide()

        self.command_panel_frame = QtWidgets.QFrame(self.centralwidget)
        self.command_panel_frame.setGeometry(QtCore.QRect(1050, 60, 171, 491))
        self.command_panel_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                               "border-radius: 13px;")
        self.command_panel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.command_panel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.command_panel_frame.setObjectName("command_panel_frame")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.command_panel_frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(-1, -1, 281, 461))
        self.scrollArea_2.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                        "border-radius: 13px;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 281, 461))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 21, 151, 51))
        self.pushButton_8.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 90, 151, 51))
        self.pushButton_9.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # Window
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        # button
        self.pushButton_3.setText(_translate("MainWindow", "setting"))
        self.rule_command_button.setText(_translate("MainWindow", "ruling command"))
        self.pushButton_7.setText(_translate("MainWindow", "q&&a"))
        # self.pushButton_17.setText(_translate("MainWindow", "youtube"))
        # self.pushButton_18.setText(_translate("MainWindow", "GitKraken"))
        self.pushButton_19.setText(_translate("MainWindow", "delite"))
        self.pushButton_8.setText(_translate("MainWindow", "command 1"))
        self.pushButton_9.setText(_translate("MainWindow", " command 2"))
        self.rule_command_back_button.setText(_translate("MainWindow", "back"))

        # lineedit
        self.lineEdit_2.setText(_translate("MainWindow", "enter name command"))
        self.lineEdit_4.setText(_translate("MainWindow", "set site"))

        # label ru
        self.label_3.setText(_translate("MainWindow", "          Семпай,надеюсь, ты меня не просто так позвал?"))
        self.label_5.setText(_translate("MainWindow", "Если хочешь быстрый доступ к сайту то\n"
                                                      " вставь ссылку"))
        self.label_4.setText(_translate("MainWindow", "     Если хочешь добавить приложение\n"
                                                      "     в быстрый запуск то *кликни* на хлеб"))
        self.lineEdit_4.setText(_translate("MainWindow", "set site"))

        # self.label_9.setText(_translate("MainWindow",
        #                                 "\"C:GamesMight & Magic.Heroes 6.Gold Edition.v 2.1.1.0 + 4 DLCMight & Magic Heroes\n"
        #                                 " VI.exe\" /offline \n"
        #                                 ""))
