# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Neko_without_frame_command.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1384, 581)
        MainWindow.setMinimumSize(QtCore.QSize(216, 0))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setStyleSheet("opacity: 0;\n"
                                 "")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        """main frame"""
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(360, 139, 731, 471))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame")
        """view character """
        self.character_label = QtWidgets.QLabel(self.frame_main)
        self.character_label.setGeometry(QtCore.QRect(360, -80, 721, 461))
        self.character_label.setText("")
        self.character_label.setPixmap(QtGui.QPixmap("material/Без имени-1 2 (1).png"))
        self.character_label.setObjectName("character_label")
        """dialog character on main frame"""
        self.dialog_character = QtWidgets.QLabel(self.frame_main)
        self.dialog_character.setGeometry(QtCore.QRect(0, 290, 491, 91))
        self.dialog_character.setStyleSheet("font-size: 18px;\n"
                                            "line-height: 40px;\n"
                                            "\n"
                                            "color: #FFFFFF;\n"
                                            "background: rgba(23, 23, 23, 0.85);\n"
                                            "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                            "border-radius: 13px;")
        self.dialog_character.setObjectName("label_3")

        """frame панели настроек - отображает кнопки: rule_command_button, q_a_button, setting_button """
        self.setting_frame = QtWidgets.QFrame(self.frame_main)
        self.setting_frame.setGeometry(QtCore.QRect(0, 80, 283, 179))
        self.setting_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                         "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                         "border-radius: 13px;")
        self.setting_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame.setObjectName("setting_frame")
        """для прокрутки setting_frame """
        self.scrollArea = QtWidgets.QScrollArea(self.setting_frame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, -1, 281, 181))
        self.scrollArea.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                      "border-radius: 13px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 181))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.setting_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setting_button.setGeometry(QtCore.QRect(40, 30, 200, 32))
        self.setting_button.setStyleSheet("border-radius: 2px;\n"
                                          "font: 12pt \"MS Shell Dlg 2\";\n"
                                          "color: rgba(255, 255, 255, 0.67);\n"
                                          "\n"
                                          "background: rgba(23, 23, 23, 0.31);\n"
                                          "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                          "box-sizing: border-box;\n"
                                          "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.setting_button.setObjectName("pushButton_3")
        """переход на add/del frame"""
        self.rule_command_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.rule_command_button.setGeometry(QtCore.QRect(40, 80, 200, 32))
        self.rule_command_button.setStyleSheet("border-radius: 2px;\n"
                                               "font: 12pt \"MS Shell Dlg 2\";\n"
                                               "color: rgba(255, 255, 255, 0.67);\n"
                                               "\n"
                                               "background: rgba(23, 23, 23, 0.31);\n"
                                               "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                               "box-sizing: border-box;\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.rule_command_button.setObjectName("rule_command_button")
        self.q_a_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.q_a_button.setGeometry(QtCore.QRect(40, 130, 200, 32))
        self.q_a_button.setStyleSheet("border-radius: 2px;\n"
                                      "font: 12pt \"MS Shell Dlg 2\";\n"
                                      "color: rgba(255, 255, 255, 0.67);\n"
                                      "\n"
                                      "background: rgba(23, 23, 23, 0.31);\n"
                                      "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                      "box-sizing: border-box;\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.q_a_button.setObjectName("teg_icon_button")
        self.teg_icon_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.teg_icon_button.setEnabled(True)
        self.teg_icon_button.setGeometry(QtCore.QRect(-6, 0, 61, 61))
        self.teg_icon_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                           "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                           "border-radius: 13px;")
        self.teg_icon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("material/image 42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.teg_icon_button.setIcon(icon)
        self.teg_icon_button.setIconSize(QtCore.QSize(50, 50))
        self.teg_icon_button.setAutoDefault(False)
        self.teg_icon_button.setDefault(False)
        self.teg_icon_button.setObjectName("teg_icon_button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        """ frame с иконками других фреймов содержит button_note,like_command_button,teg_button"""
        self.frame_icon_other_frame = QtWidgets.QFrame(self.frame_main)
        self.frame_icon_other_frame.setGeometry(QtCore.QRect(580, 90, 91, 217))
        self.frame_icon_other_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                                  "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                                  "border-radius: 13px;")
        self.frame_icon_other_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_other_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_other_frame.setObjectName("frame_icon_other_frame")
        self.button_note = QtWidgets.QPushButton(self.frame_icon_other_frame)
        self.button_note.setEnabled(True)
        self.button_note.setGeometry(QtCore.QRect(14, 10, 61, 61))
        self.button_note.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                       "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                       "border-radius: 13px;")
        self.button_note.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("material/image 40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_note.setIcon(icon1)
        self.button_note.setIconSize(QtCore.QSize(50, 50))
        self.button_note.setAutoDefault(False)
        self.button_note.setDefault(False)
        self.button_note.setObjectName("button_note")
        self.like_command_button = QtWidgets.QPushButton(self.frame_icon_other_frame)
        self.like_command_button.setEnabled(True)
        self.like_command_button.setGeometry(QtCore.QRect(14, 76, 61, 61))
        self.like_command_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                               "border-radius: 13px;")
        self.like_command_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("material/image 41.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.like_command_button.setIcon(icon2)
        self.like_command_button.setIconSize(QtCore.QSize(50, 50))
        self.like_command_button.setAutoDefault(False)
        self.like_command_button.setDefault(False)
        self.like_command_button.setObjectName("like_command_button")
        self.teg_button = QtWidgets.QPushButton(self.frame_icon_other_frame)
        self.teg_button.setEnabled(True)
        self.teg_button.setGeometry(QtCore.QRect(14, 136, 61, 61))
        self.teg_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;")
        self.teg_button.setText("")
        self.teg_button.setIcon(icon)
        self.teg_button.setIconSize(QtCore.QSize(50, 50))
        self.teg_button.setAutoDefault(False)
        self.teg_button.setDefault(False)
        self.teg_button.setObjectName("teg_button")

        """ frame add/del """
        self.frame_rule_command = QtWidgets.QFrame(self.centralwidget)
        self.frame_rule_command.setGeometry(QtCore.QRect(19, 19, 1361, 561))
        self.frame_rule_command.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rule_command.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rule_command.setObjectName("frame_rule_command")

        """фрейм где отображается выбор кнопок для удаления"""
        self.frame_choice_del_button = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_choice_del_button.setGeometry(QtCore.QRect(270, 480, 661, 81))
        self.frame_choice_del_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                                   "border-radius: 13px;")
        self.frame_choice_del_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choice_del_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choice_del_button.setObjectName("frame_choice_del_button")
        """расширение контейнера frame_choice_del_button """
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_choice_del_button)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 7, 641, 71))
        self.scrollArea_3.setStyleSheet(" QScrollBar:horizontal {\n"
                                        "    border: none;\n"
                                        "    background: rgb(23, 23, 23);\n"
                                        "    border-radius: 10px;\n"
                                        "\n"
                                        "    hight: 5px;\n"
                                        "    margin: 8px -20px 0px -30px;\n"
                                        "    \n"
                                        " }\n"
                                        "\n"
                                        "/*  HANDLE BAR VERTICAL */\n"
                                        "QScrollBar::handle:horizontal {    \n"
                                        "    background-color: rgba(255, 255, 255, 0.67);\n"
                                        "    max-height: 4px;\n"
                                        "    max-width: 10px;\n"
                                        "    border-radius: 10px;\n"
                                        "\n"
                                        "}\n"
                                        "/* BTN TOP - SCROLLBAR */\n"
                                        "QScrollBar::sub-line:horizontal {\n"
                                        "    border: none;\n"
                                        "    \n"
                                        "    width:0 px;\n"
                                        "    border-top-left-radius: 7px;\n"
                                        "    border-top-right-radius: 7px;\n"
                                        "    subcontrol-position: left;\n"
                                        "    subcontrol-origin: margin;\n"
                                        "}\n"
                                        "/* RESET ARROW */\n"
                                        "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
                                        "    background: none;\n"
                                        "}\n"
                                        "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
                                        "    background: none;\n"
                                        "}\n"
                                        "")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_2")
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1218, 54))
        self.scrollAreaWidgetContents_3.setStyleSheet("background: rgba(23, 23, 23, 0.0);")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.Layout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.Layout.setAlignment(QtCore.Qt.AlignLeft)
        self.Layout.setObjectName("gridLayout")

        self.button_delite_command = QtWidgets.QPushButton(self.frame_rule_command)
        self.button_delite_command.setGeometry(QtCore.QRect(940, 480, 71, 61))
        self.button_delite_command.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                                 "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                                 "border-radius: 13px;\n"
                                                 "font-size: 18px;\n"
                                                 "line-height: 27px;\n"
                                                 "\n"
                                                 "color: #FFFFFF;")
        self.button_delite_command.setObjectName("button_delite_command")
        """ввод данных"""
        self.input_name_command = QtWidgets.QLineEdit(self.frame_rule_command)
        self.input_name_command.setGeometry(QtCore.QRect(480, 380, 405, 55))
        self.input_name_command.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                              "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                              "border-radius: 13px;\n"
                                              "font-size: 24px;\n"
                                              "line-height: 37px;\n"
                                              "\n"
                                              "color: rgba(255, 255, 255, 0.67);")
        self.input_name_command.setObjectName("input_name_command")

        self.push_add_command = QtWidgets.QPushButton(self.frame_rule_command)
        self.push_add_command.setGeometry(QtCore.QRect(890, 380, 46, 55))
        self.push_add_command.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                            "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                            "border-radius: 13px;\n"
                                            "font-size: 18px;\n"
                                            "line-height: 27px;\n"
                                            "\n"
                                            "color: #FFFFFF;")
        self.push_add_command.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("material/image 32.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.push_add_command.setIcon(icon3)
        self.push_add_command.setObjectName("push_add_command")
        self.frame_9 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_9.setGeometry(QtCore.QRect(510, 250, 348, 87))
        self.frame_9.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                   "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                   "border-radius: 13px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        """лэйбел подсказка"""
        self.label_help_site = QtWidgets.QLabel(self.frame_9)
        self.label_help_site.setGeometry(QtCore.QRect(10, 0, 331, 81))
        self.label_help_site.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                           "font-size: 14px;\n"
                                           "line-height: 24px;\n"
                                           "\n"
                                           "color: #FFFFFF;")
        self.label_help_site.setObjectName("label_help_site")
        self.frame_10 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_10.setGeometry(QtCore.QRect(510, 130, 348, 87))
        self.frame_10.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                    "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                    "border-radius: 13px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        """лэйбел подсказка"""
        self.label_help_folder = QtWidgets.QLabel(self.frame_10)
        self.label_help_folder.setGeometry(QtCore.QRect(0, 0, 348, 91))
        self.label_help_folder.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                             "font-size: 14px;\n"
                                             "line-height: 24px;\n"
                                             "\n"
                                             "color: #FFFFFF;")
        self.label_help_folder.setObjectName("label_help_folder")
        self.bread_button = QtWidgets.QPushButton(self.frame_rule_command)
        self.bread_button.setGeometry(QtCore.QRect(300, 100, 191, 131))
        self.bread_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                        "border-radius: 13px;\n"
                                        "font-size: 18px;\n"
                                        "line-height: 27px;\n"
                                        "\n"
                                        "color: #FFFFFF;")
        self.bread_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("material/image 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bread_button.setIcon(icon4)
        self.bread_button.setIconSize(QtCore.QSize(260, 146))
        self.bread_button.setObjectName("bread_button")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_rule_command)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 270, 151, 55))
        self.lineEdit_4.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                      "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                      "border-radius: 13px;\n"
                                      "font-size: 24px;\n"
                                      "line-height: 37px;\n"
                                      "\n"
                                      "color: rgba(255, 255, 255, 0.67);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.character_on_add_del_frame = QtWidgets.QLabel(self.frame_rule_command)
        self.character_on_add_del_frame.setGeometry(QtCore.QRect(900, 100, 201, 251))
        self.character_on_add_del_frame.setText("")
        self.character_on_add_del_frame.setPixmap(QtGui.QPixmap("material/Без имени-1 2.png"))
        self.character_on_add_del_frame.setObjectName("character_on_add_del_frame")
        self.rule_command_back_button = QtWidgets.QPushButton(self.frame_rule_command)
        self.rule_command_back_button.setGeometry(QtCore.QRect(950, 380, 81, 51))
        self.rule_command_back_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
                                                    "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                                    "border-radius: 13px;\n"
                                                    "font-size: 18px;\n"
                                                    "line-height: 27px;\n"
                                                    "\n"
                                                    "color: #FFFFFF;")
        self.rule_command_back_button.setObjectName("rule_command_back_button")
        self.frame_11 = QtWidgets.QFrame(self.frame_rule_command)
        self.frame_11.setGeometry(QtCore.QRect(10, 79, 281, 311))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")

        # сетка для отображения выбранных файлов
        # self.grid = QtWidgets.QGridLayout(self.frame_11)
        # self.label_9 = QtWidgets.QLabel(self.frame_11)
        # self.label_9.setGeometry(QtCore.QRect(170, 10, 121, 151))
        # self.label_9.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
        #                            "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
        #                            "border-radius: 13px;\n"
        #                            "font-size: 12px;\n"
        #                            "line-height: 27px;\n"
        #                            "\n"
        #                            "color: #FFFFFF;")
        # self.label_9.setObjectName("")
        # self.label_9.hide()

        self.command_panel_frame = QtWidgets.QFrame(self.centralwidget)
        self.command_panel_frame.setGeometry(QtCore.QRect(1050, 60, 171, 491))
        self.command_panel_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
                                               "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
                                               "border-radius: 13px;")
        self.command_panel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.command_panel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.command_panel_frame.setObjectName("command_panel_frame")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.command_panel_frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(-1, -1, 281, 461))
        self.scrollArea_2.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
                                        "border-radius: 13px;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 281, 461))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 21, 151, 51))
        self.pushButton_8.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 90, 151, 51))
        self.pushButton_9.setStyleSheet("border-radius: 2px;\n"
                                        "font: 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgba(255, 255, 255, 0.67);\n"
                                        "\n"
                                        "background: rgba(23, 23, 23, 0.31);\n"
                                        "border: 1px solid rgba(233, 233, 233, 0.22);\n"
                                        "box-sizing: border-box;\n"
                                        "box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # Window
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        # button
        self.setting_button.setText(_translate("MainWindow", "setting"))
        self.rule_command_button.setText(_translate("MainWindow", "ruling command"))
        self.q_a_button.setText(_translate("MainWindow", "q&&a"))
        # self.pushButton_17.setText(_translate("MainWindow", "youtube"))
        # self.pushButton_18.setText(_translate("MainWindow", "GitKraken"))
        self.button_delite_command.setText(_translate("MainWindow", "delite"))
        self.pushButton_8.setText(_translate("MainWindow", "command 1"))
        self.pushButton_9.setText(_translate("MainWindow", " command 2"))
        self.rule_command_back_button.setText(_translate("MainWindow", "back"))

        # lineedit
        self.input_name_command.setText(_translate("MainWindow", "enter name command"))
        self.label_help_site.setText(_translate("MainWindow", "set site"))

        # label ru
        self.dialog_character.setText(
            _translate("MainWindow", "          Семпай,надеюсь, ты меня не просто так позвал?"))
        self.label_help_site.setText(_translate("MainWindow", "Если хочешь быстрый доступ к сайту то\n"
                                                              " вставь ссылку"))
        self.label_help_folder.setText(_translate("MainWindow", "     Если хочешь добавить приложение\n"
                                                                "     в быстрый запуск то *кликни* на хлеб"))
        self.lineEdit_4.setText(_translate("MainWindow", "set site"))
