# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(669, 634)
        self.frame_lock_2 = QtWidgets.QFrame(Dialog)
        self.frame_lock_2.setGeometry(QtCore.QRect(120, 80, 421, 201))
        self.frame_lock_2.setStyleSheet("background: #181818;\n"
"border: 1px solid #646464;\n"
"box-sizing: border-box;\n"
"border-radius: 4px;")
        self.frame_lock_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lock_2.setObjectName("frame_lock_2")
        self.descr_2 = QtWidgets.QTextBrowser(self.frame_lock_2)
        self.descr_2.setGeometry(QtCore.QRect(50, 60, 181, 71))
        self.descr_2.setStyleSheet("font: 8pt \"NSimSun\";;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"line-height: 10px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.descr_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descr_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descr_2.setObjectName("descr_2")
        self.label_2 = QtWidgets.QLabel(self.frame_lock_2)
        self.label_2.setGeometry(QtCore.QRect(250, 22, 101, 131))
        self.label_2.setStyleSheet("background: rgba(44, 40, 40, 0.0);\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../material/Firo_s.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(90, 220, 536, 168))
        self.frame.setStyleSheet("background: rgba(44, 40, 40, 0.0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setGeometry(QtCore.QRect(510, 0, 21, 23))
        self.button_close.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"line-height: 18px;\n"
"border: 0px solid #646464;\n"
"color: rgba(255, 255, 255, 0.8);background: rgba(23, 23, 23, 0.0);}\n"
"QPushButton:hover{\n"
"color: rgba(255, 255, 255, 1.0)\n"
"}")
        self.button_close.setObjectName("button_close")
        self.time_label = QtWidgets.QTextBrowser(self.frame)
        self.time_label.setGeometry(QtCore.QRect(470, 140, 61, 31))
        self.time_label.setStyleSheet("font: 8pt \"NSimSun\";;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"line-height: 10px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.time_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.time_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.time_label.setObjectName("time_label")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 110, 111, 101))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.descr_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'NSimSun\'; font-size:13px; font-weight:200; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">Loading...</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Firo: I\'m in a hurry, but you have to wait!</span></p></body></html>"))
        self.button_close.setText(_translate("Dialog", "X"))
        self.time_label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'NSimSun\'; font-size:13px; font-weight:200; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
