# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firo_parser_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 682)
        MainWindow.setStyleSheet("background: #282828;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 632, 452, 53))
        self.pushButton.setMinimumSize(QtCore.QSize(452, 53))
        self.pushButton.setMaximumSize(QtCore.QSize(452, 53))
        self.pushButton.setStyleSheet("\n"
"font: 8pt \"NSimSun\";\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 24px;\n"
"line-height: 32px;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"background: #101010;")
        self.pushButton.setObjectName("pushButton")
        self.sub_top_frame = QtWidgets.QFrame(self.centralwidget)
        self.sub_top_frame.setGeometry(QtCore.QRect(0, 25, 452, 86))
        self.sub_top_frame.setMinimumSize(QtCore.QSize(452, 86))
        self.sub_top_frame.setMaximumSize(QtCore.QSize(452, 86))
        self.sub_top_frame.setStyleSheet("background: #0C0C0C;")
        self.sub_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sub_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_top_frame.setObjectName("sub_top_frame")
        self.find_line = QtWidgets.QLineEdit(self.sub_top_frame)
        self.find_line.setGeometry(QtCore.QRect(10, 45, 420, 29))
        self.find_line.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.find_line.setInputMask("")
        self.find_line.setText("")
        self.find_line.setPlaceholderText(" type to search")
        self.find_line.setObjectName("find_line")
        self.sorted_by_mark = QtWidgets.QComboBox(self.sub_top_frame)
        self.sorted_by_mark.setGeometry(QtCore.QRect(10, 10, 206, 29))
        self.sorted_by_mark.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.sorted_by_mark.setDuplicatesEnabled(False)
        self.sorted_by_mark.setFrame(True)
        self.sorted_by_mark.setObjectName("sorted_by_mark")
        self.sorted_by_time = QtWidgets.QComboBox(self.sub_top_frame)
        self.sorted_by_time.setGeometry(QtCore.QRect(223, 10, 206, 29))
        self.sorted_by_time.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.sorted_by_time.setDuplicatesEnabled(False)
        self.sorted_by_time.setFrame(True)
        self.sorted_by_time.setObjectName("sorted_by_time")
        self.button_clear_find_page = QtWidgets.QPushButton(self.sub_top_frame)
        self.button_clear_find_page.setGeometry(QtCore.QRect(393, 43, 31, 31))
        self.button_clear_find_page.setStyleSheet("color: rgba(255, 255, 255, 0.8);\n"
"background: rgba(199, 199, 199, 0.0);\n"
"font-size: 18px;\n"
"border-top:0px solid rgb(46, 46, 46);")
        self.button_clear_find_page.setObjectName("button_clear_find_page")
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 452, 25))
        self.topbar.setMinimumSize(QtCore.QSize(452, 25))
        self.topbar.setMaximumSize(QtCore.QSize(452, 25))
        self.topbar.setStyleSheet("background: #212226;")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.button_X = QtWidgets.QPushButton(self.topbar)
        self.button_X.setGeometry(QtCore.QRect(419, 2, 31, 23))
        self.button_X.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.button_X.setObjectName("button_X")
        self.button_swap_2 = QtWidgets.QPushButton(self.topbar)
        self.button_swap_2.setGeometry(QtCore.QRect(400, 2, 21, 23))
        self.button_swap_2.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.button_swap_2.setObjectName("button_swap_2")
        self.button_setting = QtWidgets.QPushButton(self.topbar)
        self.button_setting.setGeometry(QtCore.QRect(360, 2, 21, 23))
        self.button_setting.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.button_setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../library/lib_material/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_setting.setIcon(icon)
        self.button_setting.setObjectName("button_setting")
        self.tutorial_button = QtWidgets.QPushButton(self.topbar)
        self.tutorial_button.setGeometry(QtCore.QRect(380, 2, 21, 23))
        self.tutorial_button.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.tutorial_button.setObjectName("tutorial_button")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.topbar)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 0, 221, 21))
        self.textBrowser_4.setStyleSheet("font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 13px;\n"
"line-height: 17px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 110, 451, 519))
        self.frame.setMinimumSize(QtCore.QSize(451, 321))
        self.frame.setMaximumSize(QtCore.QSize(451, 521))
        self.frame.setStyleSheet("background: rgba(44, 40, 40, 0.0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.area_for_item = QtWidgets.QScrollArea(self.frame)
        self.area_for_item.setGeometry(QtCore.QRect(10, 20, 416, 501))
        self.area_for_item.setMinimumSize(QtCore.QSize(416, 300))
        self.area_for_item.setMaximumSize(QtCore.QSize(416, 501))
        self.area_for_item.setStyleSheet("background: rgba(44, 40, 40, 0.0);")
        self.area_for_item.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_for_item.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_for_item.setWidgetResizable(True)
        self.area_for_item.setObjectName("area_for_item")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 416, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(398, 182))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 182))
        self.groupBox.setStyleSheet("background: rgba(44, 40, 40, 0.0);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 398, 51))
        self.frame_2.setStyleSheet("background: #181818;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.label_2.setStyleSheet("background: rgba(44, 40, 40, 0.0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../material/mark_icon/bell.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(60, 4, 221, 21))
        self.textBrowser.setStyleSheet("font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 13px;\n"
"line-height: 17px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: #FFFFFF;\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 26, 181, 21))
        self.textBrowser_2.setStyleSheet("font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 13px;\n"
"line-height: 17px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pause = QtWidgets.QPushButton(self.frame_2)
        self.pause.setGeometry(QtCore.QRect(300, 13, 21, 21))
        self.pause.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../material/pause_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon1)
        self.pause.setIconSize(QtCore.QSize(14, 10))
        self.pause.setObjectName("pause")
        self.pause_2 = QtWidgets.QPushButton(self.frame_2)
        self.pause_2.setGeometry(QtCore.QRect(330, 13, 21, 21))
        self.pause_2.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.pause_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../material/good_connect_ver_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_2.setIcon(icon2)
        self.pause_2.setIconSize(QtCore.QSize(16, 20))
        self.pause_2.setObjectName("pause_2")
        self.pause_3 = QtWidgets.QPushButton(self.frame_2)
        self.pause_3.setGeometry(QtCore.QRect(360, 13, 21, 21))
        self.pause_3.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.pause_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../material/tree_point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_3.setIcon(icon3)
        self.pause_3.setIconSize(QtCore.QSize(20, 20))
        self.pause_3.setObjectName("pause_3")
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setGeometry(QtCore.QRect(0, 53, 398, 131))
        self.frame_3.setStyleSheet("background: #181818;\n"
"border: 1px solid #646464;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.textBrowser_3.setStyleSheet("font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 13px;\n"
"line-height: 10px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.area_for_item.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(435, 20, 4, 450))
        self.label.setStyleSheet("background: #0C0C0C;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "-- serfing --"))
        self.button_clear_find_page.setText(_translate("MainWindow", "X"))
        self.button_X.setText(_translate("MainWindow", "X"))
        self.button_swap_2.setText(_translate("MainWindow", "—"))
        self.tutorial_button.setText(_translate("MainWindow", "?"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:13px; font-weight:296; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Firo\'s parser</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:13px; font-weight:296; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">https://www.figma.com<br /><br /></span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:13px; font-weight:296; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">element: 10 uncheced: 5</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Mono\'; font-size:13px; font-weight:296; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Sait: </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">teg:                          element:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">action:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">mark:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
