# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_add_label_parse.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 190)
        Dialog.setStyleSheet("background: #181818;\n"
"border: 1px solid #646464;")
        self.descr = QtWidgets.QTextBrowser(Dialog)
        self.descr.setGeometry(QtCore.QRect(10, 20, 431, 161))
        self.descr.setStyleSheet("font: 8pt \"NSimSun\";;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"line-height: 10px;\n"
"text-decoration-line: underline;\n"
"background: rgba(44, 40, 40, 0.0);\n"
"color: rgba(255, 255, 255, 0.8);\n"
"\n"
"border: 0.5px solid rgba(167, 167, 167, 0.0);")
        self.descr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descr.setObjectName("descr")
        self.teg_choice = QtWidgets.QComboBox(Dialog)
        self.teg_choice.setGeometry(QtCore.QRect(70, 61, 151, 20))
        self.teg_choice.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.teg_choice.setDuplicatesEnabled(False)
        self.teg_choice.setFrame(True)
        self.teg_choice.setObjectName("teg_choice")
        self.action_choice = QtWidgets.QComboBox(Dialog)
        self.action_choice.setGeometry(QtCore.QRect(70, 100, 151, 20))
        self.action_choice.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.action_choice.setDuplicatesEnabled(False)
        self.action_choice.setFrame(True)
        self.action_choice.setObjectName("action_choice")
        self.sait_line = QtWidgets.QLineEdit(Dialog)
        self.sait_line.setGeometry(QtCore.QRect(70, 28, 241, 20))
        self.sait_line.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.sait_line.setInputMask("")
        self.sait_line.setText("")
        self.sait_line.setPlaceholderText("your sait")
        self.sait_line.setObjectName("sait_line")
        self.mark_line = QtWidgets.QLineEdit(Dialog)
        self.mark_line.setGeometry(QtCore.QRect(70, 150, 291, 20))
        self.mark_line.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.mark_line.setInputMask("")
        self.mark_line.setText("")
        self.mark_line.setPlaceholderText("maybe you want marked this?")
        self.mark_line.setObjectName("mark_line")
        self.element_choice = QtWidgets.QComboBox(Dialog)
        self.element_choice.setGeometry(QtCore.QRect(320, 60, 151, 20))
        self.element_choice.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.element_choice.setDuplicatesEnabled(False)
        self.element_choice.setFrame(True)
        self.element_choice.setObjectName("element_choice")
        self.continue_button = QtWidgets.QPushButton(Dialog)
        self.continue_button.setGeometry(QtCore.QRect(420, 150, 81, 23))
        self.continue_button.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"line-height: 18px;\n"
"border: 0px solid #646464;\n"
"color: rgba(255, 255, 255, 0.8);background: rgba(23, 23, 23, 0.0);}\n"
"QPushButton:hover{\n"
"color: rgba(255, 255, 255, 1.0)\n"
"}")
        self.continue_button.setObjectName("continue_button")
        self.button_close = QtWidgets.QPushButton(Dialog)
        self.button_close.setGeometry(QtCore.QRect(490, 0, 21, 23))
        self.button_close.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"line-height: 18px;\n"
"border: 0px solid #646464;\n"
"color: rgba(255, 255, 255, 0.8);background: rgba(23, 23, 23, 0.0);}\n"
"QPushButton:hover{\n"
"color: rgba(255, 255, 255, 1.0)\n"
"}")
        self.button_close.setObjectName("button_close")
        self.value_line = QtWidgets.QLineEdit(Dialog)
        self.value_line.setGeometry(QtCore.QRect(250, 100, 191, 20))
        self.value_line.setStyleSheet("background: #2B2B2B;\n"
"border-radius: 4px;\n"
"font-family: \'Roboto Mono\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 18px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);\n"
"")
        self.value_line.setInputMask("")
        self.value_line.setText("")
        self.value_line.setPlaceholderText("input value")
        self.value_line.setObjectName("value_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.descr.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'NSimSun\'; font-size:13px; font-weight:200; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\">Sait: </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\">teg:                                          element:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\">action:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Roboto Mono\'; font-weight:296;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto Mono\'; font-size:11pt; font-weight:296;\">mark:</span></p></body></html>"))
        self.continue_button.setText(_translate("Dialog", "continue"))
        self.button_close.setText(_translate("Dialog", "X"))
