# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'junk.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 160, 188, 256))
        self.groupBox.setMinimumSize(QtCore.QSize(188, 256))
        self.groupBox.setMaximumSize(QtCore.QSize(188, 256))
        self.groupBox.setStyleSheet("background: #161616;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 8px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 168, 182))
        self.label.setStyleSheet("border-radius: 20px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../material/LkuRp57vMSwa_250x350.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(20, 200, 151, 41))
        self.textBrowser.setStyleSheet("font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"\n"
"color: rgba(255, 255, 255, 0.8);")
        self.textBrowser.setObjectName("textBrowser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 60, 61, 22))
        self.frame.setStyleSheet("background: #000000;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 0, 31, 23))
        self.pushButton.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(3, 0, 31, 23))
        self.pushButton_2.setStyleSheet("color: #FFFFFF;\n"
"background: rgba(199, 199, 199, 0.0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 230, 121, 1))
        self.label_3.setStyleSheet("background: rgba(167, 167, 167, 0.7);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 130, 221, 311))
        self.groupBox_2.setMinimumSize(QtCore.QSize(221, 311))
        self.groupBox_2.setMaximumSize(QtCore.QSize(221, 16777215))
        self.groupBox_2.setStyleSheet("background: #1B1B1B;\n"
"box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.85);\n"
"border-radius: 8px;\n"
"padding: 0px 20px  20px 20px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 201, 231))
        self.label_4.setStyleSheet("border-radius: 20px;\n"
"padding: 0px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../material/LkuRp57vMSwa_250x350.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 260, 171, 41))
        self.textBrowser_5.setStyleSheet("font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"padding: 0px;\n"
"color: rgba(255, 255, 255, 0.8);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(12, 170, 211, 311))
        self.groupBox_3.setStyleSheet("background: #1B1B1B;\n"
"box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.85);\n"
"border-radius: 8px;\n"
"padding: 0px 20px  20px 20px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(4, 10, 201, 231))
        self.label_6.setStyleSheet("border-radius: 20px;\n"
"padding: 0px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../material/LkuRp57vMSwa_250x350.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(20, 260, 171, 41))
        self.textBrowser_7.setStyleSheet("font-family: \'Montserrat\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"padding: 0px;\n"
"color: rgba(255, 255, 255, 0.8);")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.page_book_widget_3_pos = QtWidgets.QWidget(self.centralwidget)
        self.page_book_widget_3_pos.setGeometry(QtCore.QRect(920, 190, 802, 621))
        self.page_book_widget_3_pos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.556818, x2:1, y2:0, stop:0 rgba(27, 27, 27, 255), stop:1 rgba(22, 22, 22, 255));")
        self.page_book_widget_3_pos.setObjectName("page_book_widget_3_pos")
        self.recent_book_container = QtWidgets.QGroupBox(self.page_book_widget_3_pos)
        self.recent_book_container.setGeometry(QtCore.QRect(0, 0, 791, 371))
        self.recent_book_container.setStyleSheet("border: 0.5px solid rgba(167, 167, 167, 0.0);\n"
"background: linear-gradient(180deg, #202020 0%, #0F0F0F 100%);")
        self.recent_book_container.setTitle("")
        self.recent_book_container.setObjectName("recent_book_container")
        self.name_container = QtWidgets.QTextBrowser(self.recent_book_container)
        self.name_container.setGeometry(QtCore.QRect(20, 10, 421, 41))
        self.name_container.setStyleSheet("font-family: \'RobotoFlex\';\n"
"font-style: normal;\n"
"font-weight: 200;\n"
"font-size: 13px;\n"
"line-height: 75.4%;\n"
"/* or 14px */\n"
"background: rgba(199, 199, 199, 0.0);\n"
"border: 0.5px solid rgba(167, 167, 167, 0.01);\n"
"color: rgba(255, 255, 255, 0.85);\n"
"")
        self.name_container.setObjectName("name_container")
        self.area_for_book = QtWidgets.QScrollArea(self.recent_book_container)
        self.area_for_book.setGeometry(QtCore.QRect(0, 38, 801, 581))
        self.area_for_book.setStyleSheet("padding: 15px 7px  5px 7px;\n"
"background: rgba(199, 199, 199, 0.0);\n"
"margin: 0 5px 10px 5px;")
        self.area_for_book.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_for_book.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_for_book.setWidgetResizable(True)
        self.area_for_book.setObjectName("area_for_book")
        self.area_for_book_container = QtWidgets.QWidget()
        self.area_for_book_container.setGeometry(QtCore.QRect(0, 0, 769, 549))
        self.area_for_book_container.setObjectName("area_for_book_container")
        self.gridLayout = QtWidgets.QGridLayout(self.area_for_book_container)
        self.gridLayout.setObjectName("gridLayout")
        self.area_for_book.setWidget(self.area_for_book_container)
        self.button_all = QtWidgets.QPushButton(self.recent_book_container)
        self.button_all.setGeometry(QtCore.QRect(730, 20, 41, 23))
        self.button_all.setStyleSheet("color: #FFFFFF;\n"
"text-decoration: underline;\n"
"font: 75 8pt \"Arial\";\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"background: rgba(199, 199, 199, 8.0);\n"
"font-family: \'RobotoFlex\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"letter-spacing: 0.115em;")
        self.button_all.setObjectName("button_all")
        self.button_back = QtWidgets.QPushButton(self.recent_book_container)
        self.button_back.setGeometry(QtCore.QRect(730, 10, 41, 31))
        self.button_back.setStyleSheet("color: #FFFFFF;\n"
"text-decoration: underline;\n"
"font: 75 8pt \"Arial\";\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"background: rgba(199, 199, 199, 8.0);\n"
"font-family: \'RobotoFlex\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 18px;\n"
"letter-spacing: 0.115em;")
        self.button_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../library/lib_material/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back.setIcon(icon)
        self.button_back.setIconSize(QtCore.QSize(33, 28))
        self.button_back.setObjectName("button_back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Montserrat\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">rise hero shield</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_2.setText(_translate("MainWindow", "—"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Montserrat\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">rise hero shield</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Montserrat\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">rise hero shield</span></p></body></html>"))
        self.name_container.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'RobotoFlex\'; font-size:13px; font-weight:200; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Recent</span></p></body></html>"))
        self.button_all.setText(_translate("MainWindow", "All"))
