# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rebuild.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 767)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, -1, 1311, 761))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main_frame = QtWidgets.QWidget()
        self.page_main_frame.setObjectName("page_main_frame")
        self.mainframe = QtWidgets.QFrame(self.page_main_frame)
        self.mainframe.setGeometry(QtCore.QRect(290, 80, 911, 571))
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.character_label = QtWidgets.QLabel(self.mainframe)
        self.character_label.setGeometry(QtCore.QRect(390, 190, 171, 241))
        self.character_label.setText("")
        self.character_label.setPixmap(QtGui.QPixmap("material/Firo/Firo_setting.png"))
        self.character_label.setObjectName("character_label")
        self.dialog_character = QtWidgets.QLabel(self.mainframe)
        self.dialog_character.setGeometry(QtCore.QRect(50, 430, 471, 81))
        self.dialog_character.setStyleSheet("font-size: 18px;\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"background: rgba(23, 23, 23, 0.85);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.dialog_character.setAlignment(QtCore.Qt.AlignCenter)
        self.dialog_character.setObjectName("dialog_character")
        self.teg_list_frame = QtWidgets.QFrame(self.mainframe)
        self.teg_list_frame.setGeometry(QtCore.QRect(60, 230, 283, 179))
        self.teg_list_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.teg_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teg_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teg_list_frame.setObjectName("teg_list_frame")
        self.teg_area = QtWidgets.QScrollArea(self.teg_list_frame)
        self.teg_area.setGeometry(QtCore.QRect(-1, -1, 281, 181))
        self.teg_area.setStyleSheet("background: rgba(23, 23, 23, 0);\n"
"border-radius: 13px;")
        self.teg_area.setWidgetResizable(True)
        self.teg_area.setObjectName("teg_area")
        self.teg_area_container = QtWidgets.QWidget()
        self.teg_area_container.setGeometry(QtCore.QRect(0, 0, 281, 181))
        self.teg_area_container.setObjectName("teg_area_container")
        self.setting_button = QtWidgets.QPushButton(self.teg_area_container)
        self.setting_button.setGeometry(QtCore.QRect(40, 30, 200, 32))
        self.setting_button.setStyleSheet("border-radius: 2px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgba(255, 255, 255, 0.67);\n"
"\n"
"background: rgba(23, 23, 23, 0.31);\n"
"border: 1px solid rgba(233, 233, 233, 0.22);\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.setting_button.setObjectName("setting_button")
        self.rule_button = QtWidgets.QPushButton(self.teg_area_container)
        self.rule_button.setGeometry(QtCore.QRect(40, 80, 200, 32))
        self.rule_button.setStyleSheet("border-radius: 2px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgba(255, 255, 255, 0.67);\n"
"\n"
"background: rgba(23, 23, 23, 0.31);\n"
"border: 1px solid rgba(233, 233, 233, 0.22);\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.rule_button.setObjectName("rule_button")
        self.q_a_button = QtWidgets.QPushButton(self.teg_area_container)
        self.q_a_button.setGeometry(QtCore.QRect(40, 130, 200, 32))
        self.q_a_button.setStyleSheet("border-radius: 2px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgba(255, 255, 255, 0.67);\n"
"\n"
"background: rgba(23, 23, 23, 0.31);\n"
"border: 1px solid rgba(233, 233, 233, 0.22);\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);")
        self.q_a_button.setObjectName("q_a_button")
        self.teg_area.setWidget(self.teg_area_container)
        self.frame_icon_other_frame = QtWidgets.QFrame(self.mainframe)
        self.frame_icon_other_frame.setGeometry(QtCore.QRect(580, 150, 91, 291))
        self.frame_icon_other_frame.setStyleSheet("background: rgba(23, 23, 23, 0.83);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.frame_icon_other_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_other_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_other_frame.setObjectName("frame_icon_other_frame")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_icon_other_frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 9, 72, 281))
        self.scrollArea_2.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 72, 281))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tag_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.tag_button.setEnabled(True)
        self.tag_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.tag_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("material/image 42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tag_button.setIcon(icon)
        self.tag_button.setIconSize(QtCore.QSize(50, 50))
        self.tag_button.setAutoDefault(False)
        self.tag_button.setDefault(False)
        self.tag_button.setObjectName("tag_button")
        self.gridLayout.addWidget(self.tag_button, 3, 0, 1, 1)
        self.button_note = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.button_note.setEnabled(True)
        self.button_note.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.button_note.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("material/image 50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_note.setIcon(icon1)
        self.button_note.setIconSize(QtCore.QSize(50, 50))
        self.button_note.setAutoDefault(False)
        self.button_note.setDefault(False)
        self.button_note.setObjectName("button_note")
        self.gridLayout.addWidget(self.button_note, 0, 0, 1, 1)
        self.command_list_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.command_list_button.setEnabled(True)
        self.command_list_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.command_list_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("material/image 41.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.command_list_button.setIcon(icon2)
        self.command_list_button.setIconSize(QtCore.QSize(50, 50))
        self.command_list_button.setAutoDefault(False)
        self.command_list_button.setDefault(False)
        self.command_list_button.setObjectName("command_list_button")
        self.gridLayout.addWidget(self.command_list_button, 1, 0, 1, 1)
        self.remain_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.remain_button.setEnabled(True)
        self.remain_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.remain_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("material/image 63.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remain_button.setIcon(icon3)
        self.remain_button.setIconSize(QtCore.QSize(50, 50))
        self.remain_button.setAutoDefault(False)
        self.remain_button.setDefault(False)
        self.remain_button.setObjectName("remain_button")
        self.gridLayout.addWidget(self.remain_button, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.stackedWidget.addWidget(self.page_main_frame)
        self.page_add_frame = QtWidgets.QWidget()
        self.page_add_frame.setObjectName("page_add_frame")
        self.stacked_add_frame = QtWidgets.QStackedWidget(self.page_add_frame)
        self.stacked_add_frame.setGeometry(QtCore.QRect(30, 10, 1281, 741))
        self.stacked_add_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stacked_add_frame.setObjectName("stacked_add_frame")
        self.page_add_1 = QtWidgets.QWidget()
        self.page_add_1.setObjectName("page_add_1")
        self.lineedit_command = QtWidgets.QLineEdit(self.page_add_1)
        self.lineedit_command.setGeometry(QtCore.QRect(220, 520, 374, 55))
        self.lineedit_command.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 12px;\n"
"font-size: 24px;\n"
"line-height: 37px;\n"
"\n"
"color: rgba(255, 255, 255, 0.67);")
        self.lineedit_command.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_command.setObjectName("lineedit_command")
        self.label_add_1 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_1.setGeometry(QtCore.QRect(230, 30, 371, 29))
        self.label_add_1.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_1.setObjectName("label_add_1")
        self.label_add_4 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_4.setGeometry(QtCore.QRect(350, 240, 231, 29))
        self.label_add_4.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_4.setObjectName("label_add_4")
        self.save_command_button = QtWidgets.QPushButton(self.page_add_1)
        self.save_command_button.setGeometry(QtCore.QRect(260, 590, 286, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_command_button.sizePolicy().hasHeightForWidth())
        self.save_command_button.setSizePolicy(sizePolicy)
        self.save_command_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_command_button.setAutoFillBackground(False)
        self.save_command_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 12px;\n"
"font-size: 24px;\n"
"line-height: 37px;\n"
"\n"
"color: rgba(255, 255, 255, 0.67);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("material/image 32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_command_button.setIcon(icon4)
        self.save_command_button.setObjectName("save_command_button")
        self.label_add_click_1 = QtWidgets.QLabel(self.page_add_1)
        self.label_add_click_1.setGeometry(QtCore.QRect(120, 90, 61, 31))
        self.label_add_click_1.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_click_1.setObjectName("label_add_click_1")
        self.label_29 = QtWidgets.QLabel(self.page_add_1)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 172, 137))
        self.label_29.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;")
        self.label_29.setObjectName("label_29")
        self.label_add_7 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_7.setGeometry(QtCore.QRect(230, 440, 31, 29))
        self.label_add_7.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_7.setObjectName("label_add_7")
        self.lineedit_site = QtWidgets.QLineEdit(self.page_add_1)
        self.lineedit_site.setGeometry(QtCore.QRect(230, 300, 346, 42))
        self.lineedit_site.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 12px;\n"
"font-size: 24px;\n"
"line-height: 37px;\n"
"\n"
"color: rgba(255, 255, 255, 0.67);")
        self.lineedit_site.setAlignment(QtCore.Qt.AlignCenter)
        self.lineedit_site.setObjectName("lineedit_site")
        self.label_add_6 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_6.setGeometry(QtCore.QRect(230, 400, 141, 29))
        self.label_add_6.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_6.setObjectName("label_add_6")
        self.character_add_label = QtWidgets.QLabel(self.page_add_1)
        self.character_add_label.setGeometry(QtCore.QRect(20, 0, 121, 151))
        self.character_add_label.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.character_add_label.setText("")
        self.character_add_label.setPixmap(QtGui.QPixmap("material/Firo/Firo_s.png"))
        self.character_add_label.setObjectName("character_add_label")
        self.label_add_2 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_2.setGeometry(QtCore.QRect(230, 70, 251, 29))
        self.label_add_2.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_2.setObjectName("label_add_2")
        self.label_add_5 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_5.setGeometry(QtCore.QRect(230, 360, 291, 29))
        self.label_add_5.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_5.setObjectName("label_add_5")
        self.label_add_click_3 = QtWidgets.QLabel(self.page_add_1)
        self.label_add_click_3.setGeometry(QtCore.QRect(1195, 506, 61, 31))
        self.label_add_click_3.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_click_3.setObjectName("label_add_click_3")
        self.back_from_add_button = QtWidgets.QPushButton(self.page_add_1)
        self.back_from_add_button.setGeometry(QtCore.QRect(20, 200, 171, 38))
        self.back_from_add_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 10px;\n"
"font-size: 14px;\n"
"line-height: 27px;\n"
"\n"
"color: #FFFFFF;")
        self.back_from_add_button.setObjectName("back_from_add_button")
        self.background_bread_button = QtWidgets.QFrame(self.page_add_1)
        self.background_bread_button.setGeometry(QtCore.QRect(260, 150, 317, 77))
        self.background_bread_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 12px;")
        self.background_bread_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_bread_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_bread_button.setObjectName("background_bread_button")
        self.bread_button_2 = QtWidgets.QPushButton(self.background_bread_button)
        self.bread_button_2.setGeometry(QtCore.QRect(0, -10, 137, 79))
        self.bread_button_2.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 18px;\n"
"line-height: 27px;\n"
"\n"
"color: #FFFFFF;")
        self.bread_button_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("material/image 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bread_button_2.setIcon(icon5)
        self.bread_button_2.setIconSize(QtCore.QSize(155, 99))
        self.bread_button_2.setObjectName("bread_button_2")
        self.label_add_click_2 = QtWidgets.QLabel(self.background_bread_button)
        self.label_add_click_2.setGeometry(QtCore.QRect(130, 30, 61, 31))
        self.label_add_click_2.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_click_2.setObjectName("label_add_click_2")
        self.file_button = QtWidgets.QPushButton(self.background_bread_button)
        self.file_button.setEnabled(True)
        self.file_button.setGeometry(QtCore.QRect(230, 10, 56, 52))
        self.file_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.file_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("material/image 75.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_button.setIcon(icon6)
        self.file_button.setIconSize(QtCore.QSize(50, 50))
        self.file_button.setAutoDefault(False)
        self.file_button.setDefault(False)
        self.file_button.setObjectName("file_button")
        self.label_add_click_4 = QtWidgets.QLabel(self.page_add_1)
        self.label_add_click_4.setGeometry(QtCore.QRect(1195, 636, 61, 31))
        self.label_add_click_4.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_click_4.setObjectName("label_add_click_4")
        self.card_board_box_button = QtWidgets.QPushButton(self.page_add_1)
        self.card_board_box_button.setEnabled(True)
        self.card_board_box_button.setGeometry(QtCore.QRect(1170, 430, 102, 106))
        self.card_board_box_button.setStyleSheet("background: rgba(33, 24, 24, 0.6);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.card_board_box_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("material/image 78.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card_board_box_button.setIcon(icon7)
        self.card_board_box_button.setIconSize(QtCore.QSize(50, 50))
        self.card_board_box_button.setAutoDefault(False)
        self.card_board_box_button.setDefault(False)
        self.card_board_box_button.setObjectName("card_board_box_button")
        self.info_button = QtWidgets.QPushButton(self.page_add_1)
        self.info_button.setEnabled(True)
        self.info_button.setGeometry(QtCore.QRect(120, 40, 56, 52))
        self.info_button.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.info_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("material/image 74.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_button.setIcon(icon8)
        self.info_button.setIconSize(QtCore.QSize(50, 50))
        self.info_button.setAutoDefault(False)
        self.info_button.setDefault(False)
        self.info_button.setObjectName("info_button")
        self.label_add_8 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_8.setGeometry(QtCore.QRect(20, 152, 171, 41))
        self.label_add_8.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_8.setObjectName("label_add_8")
        self.label_add_3 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_3.setGeometry(QtCore.QRect(230, 110, 131, 29))
        self.label_add_3.setStyleSheet("background: rgba(233, 209, 209, 0.3);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 20px;\n"
"\n"
"color: #FFFFFF;")
        self.label_add_3.setObjectName("label_add_3")
        self.trash_can_button = QtWidgets.QPushButton(self.page_add_1)
        self.trash_can_button.setEnabled(True)
        self.trash_can_button.setGeometry(QtCore.QRect(1170, 560, 102, 106))
        self.trash_can_button.setStyleSheet("background: rgba(33, 24, 24, 0.6);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.trash_can_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("material/image 80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trash_can_button.setIcon(icon9)
        self.trash_can_button.setIconSize(QtCore.QSize(50, 50))
        self.trash_can_button.setAutoDefault(False)
        self.trash_can_button.setDefault(False)
        self.trash_can_button.setObjectName("trash_can_button")
        self.background_message = QtWidgets.QLabel(self.page_add_1)
        self.background_message.setGeometry(QtCore.QRect(210, 10, 395, 683))
        self.background_message.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 12px;\n"
"line-height: 27px;\n"
"\n"
"color: #FFFFFF;")
        self.background_message.setText("")
        self.background_message.setObjectName("background_message")
        self.delite_button = QtWidgets.QPushButton(self.page_add_1)
        self.delite_button.setGeometry(QtCore.QRect(1090, 560, 70, 34))
        self.delite_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 13px;\n"
"line-height: 27px;\n"
"\n"
"color: #FFFFFF;")
        self.delite_button.setObjectName("delite_button")
        self.label_about_delite = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_about_delite.setGeometry(QtCore.QRect(670, 620, 171, 41))
        self.label_about_delite.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_about_delite.setObjectName("label_about_delite")
        self.delite_area = QtWidgets.QScrollArea(self.page_add_1)
        self.delite_area.setGeometry(QtCore.QRect(670, 560, 411, 51))
        self.delite_area.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.delite_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.delite_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.delite_area.setWidgetResizable(True)
        self.delite_area.setObjectName("delite_area")
        self.delite_area_container = QtWidgets.QWidget()
        self.delite_area_container.setGeometry(QtCore.QRect(0, 0, 411, 51))
        self.delite_area_container.setStyleSheet("background: rgba(23, 23, 23, 0.0);")
        self.delite_area_container.setObjectName("delite_area_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.delite_area_container)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delite_area.setWidget(self.delite_area_container)
        self.label_info_2 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_info_2.setGeometry(QtCore.QRect(620, 290, 311, 61))
        self.label_info_2.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_info_2.setObjectName("label_info_2")
        self.label_add_13 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_add_13.setGeometry(QtCore.QRect(620, 160, 311, 61))
        self.label_add_13.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_add_13.setObjectName("label_add_13")
        self.label_info_3 = QtWidgets.QTextBrowser(self.page_add_1)
        self.label_info_3.setGeometry(QtCore.QRect(930, 380, 211, 151))
        self.label_info_3.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 6px;\n"
"font-family: \'Titillium Web\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 18px;\n"
"padding: 0 0 0 5px;\n"
"color: #FFFFFF;")
        self.label_info_3.setObjectName("label_info_3")
        self.label_29.raise_()
        self.background_message.raise_()
        self.card_board_box_button.raise_()
        self.trash_can_button.raise_()
        self.lineedit_command.raise_()
        self.label_add_1.raise_()
        self.label_add_4.raise_()
        self.save_command_button.raise_()
        self.label_add_click_1.raise_()
        self.label_add_7.raise_()
        self.lineedit_site.raise_()
        self.label_add_6.raise_()
        self.character_add_label.raise_()
        self.label_add_2.raise_()
        self.label_add_5.raise_()
        self.label_add_click_3.raise_()
        self.back_from_add_button.raise_()
        self.background_bread_button.raise_()
        self.label_add_click_4.raise_()
        self.info_button.raise_()
        self.label_add_8.raise_()
        self.label_add_3.raise_()
        self.delite_button.raise_()
        self.label_about_delite.raise_()
        self.delite_area.raise_()
        self.label_info_2.raise_()
        self.label_add_13.raise_()
        self.label_info_3.raise_()
        self.stacked_add_frame.addWidget(self.page_add_1)
        self.stackedWidget.addWidget(self.page_add_frame)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.setting_page)
        self.stackedWidget_2.setGeometry(QtCore.QRect(100, 100, 981, 481))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.setting_page_3 = QtWidgets.QWidget()
        self.setting_page_3.setObjectName("setting_page_3")
        self.setting_page_2 = QtWidgets.QFrame(self.setting_page_3)
        self.setting_page_2.setGeometry(QtCore.QRect(10, 20, 929, 445))
        self.setting_page_2.setStyleSheet("background: rgba(33, 24, 24, 0.6);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.35);\n"
"border-radius: 13px;")
        self.setting_page_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_page_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_page_2.setObjectName("setting_page_2")
        self.label_setting_page_2 = QtWidgets.QLabel(self.setting_page_2)
        self.label_setting_page_2.setGeometry(QtCore.QRect(20, 0, 71, 31))
        self.label_setting_page_2.setStyleSheet("font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 14px;\n"
"line-height: 34px;\n"
"/* identical to box height */\n"
"background: rgba(33, 24, 24, 0.0);\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_page_2.setObjectName("label_setting_page_2")
        self.label_window_page_2 = QtWidgets.QLabel(self.setting_page_2)
        self.label_window_page_2.setGeometry(QtCore.QRect(10, 56, 169, 55))
        self.label_window_page_2.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_window_page_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_window_page_2.setObjectName("label_window_page_2")
        self.label_normal_window_page_2 = QtWidgets.QLabel(self.setting_page_2)
        self.label_normal_window_page_2.setGeometry(QtCore.QRect(220, 56, 561, 55))
        self.label_normal_window_page_2.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_normal_window_page_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_normal_window_page_2.setObjectName("label_normal_window_page_2")
        self.label_page_2 = QtWidgets.QLabel(self.setting_page_2)
        self.label_page_2.setGeometry(QtCore.QRect(786, 10, 91, 31))
        self.label_page_2.setStyleSheet("background: rgba(33, 24, 24, 0.0);\n"
"font: 16pt \"Arial\";\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_page_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_2.setObjectName("label_page_2")
        self.button_window_r_2 = QtWidgets.QPushButton(self.setting_page_2)
        self.button_window_r_2.setGeometry(QtCore.QRect(740, 70, 31, 26))
        self.button_window_r_2.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_window_r_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("material/image 38.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_window_r_2.setIcon(icon10)
        self.button_window_r_2.setObjectName("button_window_r_2")
        self.button_window_l_2 = QtWidgets.QPushButton(self.setting_page_2)
        self.button_window_l_2.setGeometry(QtCore.QRect(230, 70, 31, 26))
        self.button_window_l_2.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_window_l_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("material/image 52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_window_l_2.setIcon(icon11)
        self.button_window_l_2.setObjectName("button_window_l_2")
        self.button_on_1_page = QtWidgets.QPushButton(self.setting_page_2)
        self.button_on_1_page.setGeometry(QtCore.QRect(761, 13, 31, 26))
        self.button_on_1_page.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_on_1_page.setText("")
        self.button_on_1_page.setIcon(icon11)
        self.button_on_1_page.setObjectName("button_on_1_page")
        self.stackedWidget_2.addWidget(self.setting_page_3)
        self.setting_page_1 = QtWidgets.QWidget()
        self.setting_page_1.setObjectName("setting_page_1")
        self.page_setting_1 = QtWidgets.QFrame(self.setting_page_1)
        self.page_setting_1.setGeometry(QtCore.QRect(10, 20, 929, 445))
        self.page_setting_1.setStyleSheet("background: rgba(33, 24, 24, 0.6);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.35);\n"
"border-radius: 13px;")
        self.page_setting_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_setting_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_setting_1.setObjectName("page_setting_1")
        self.label_setting = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting.setGeometry(QtCore.QRect(20, 0, 71, 31))
        self.label_setting.setStyleSheet("font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 14px;\n"
"line-height: 34px;\n"
"/* identical to box height */\n"
"background: rgba(33, 24, 24, 0.0);\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting.setObjectName("label_setting")
        self.label_setting_1 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_1.setGeometry(QtCore.QRect(10, 80, 403, 75))
        self.label_setting_1.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 11px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting_1.setObjectName("label_setting_1")
        self.label_setting_4 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_4.setGeometry(QtCore.QRect(10, 310, 169, 55))
        self.label_setting_4.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting_4.setObjectName("label_setting_4")
        self.label_setting_5 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_5.setGeometry(QtCore.QRect(10, 375, 169, 55))
        self.label_setting_5.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting_5.setObjectName("label_setting_5")
        self.label_setting_2 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_2.setGeometry(QtCore.QRect(140, 160, 141, 31))
        self.label_setting_2.setStyleSheet("font-family: Roboto Mono;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 14px;\n"
"line-height: 34px;\n"
"/* identical to box height */\n"
"background: rgba(33, 24, 24, 0.0);\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_2.setObjectName("label_setting_2")
        self.Nickname_2 = QtWidgets.QLineEdit(self.page_setting_1)
        self.Nickname_2.setGeometry(QtCore.QRect(100, 210, 226, 58))
        self.Nickname_2.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"font: 18pt \"Arial\";\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 8px;\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;")
        self.Nickname_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Nickname_2.setObjectName("Nickname_2")
        self.label_setting_6 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_6.setGeometry(QtCore.QRect(220, 310, 561, 55))
        self.label_setting_6.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting_6.setObjectName("label_setting_6")
        self.label_setting_7 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_7.setGeometry(QtCore.QRect(220, 376, 561, 55))
        self.label_setting_7.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"font: 18pt \"Arial\";\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setting_7.setObjectName("label_setting_7")
        self.character_set = QtWidgets.QLabel(self.page_setting_1)
        self.character_set.setGeometry(QtCore.QRect(470, 0, 167, 234))
        self.character_set.setStyleSheet("background: rgba(33, 24, 24, 0.0);\n"
"font: 18pt \"Arial\";\n"
"\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.character_set.setText("")
        self.character_set.setPixmap(QtGui.QPixmap("material/Firo/Firo_setting.png"))
        self.character_set.setAlignment(QtCore.Qt.AlignCenter)
        self.character_set.setObjectName("character_set")
        self.button_save = QtWidgets.QPushButton(self.page_setting_1)
        self.button_save.setGeometry(QtCore.QRect(800, 310, 106, 55))
        self.button_save.setStyleSheet("background: rgba(23, 23, 23, 0.8);\n"
"border: 1px solid #B19696;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 26px;\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.button_save.setObjectName("button_save")
        self.back_fome_setting_button = QtWidgets.QPushButton(self.page_setting_1)
        self.back_fome_setting_button.setGeometry(QtCore.QRect(800, 370, 106, 55))
        self.back_fome_setting_button.setStyleSheet("background: rgba(23, 23, 23, 0.8);\n"
"border: 1px solid #B19696;\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 26px;\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.back_fome_setting_button.setObjectName("back_fome_setting_button")
        self.label_setting_8 = QtWidgets.QLabel(self.page_setting_1)
        self.label_setting_8.setGeometry(QtCore.QRect(720, 56, 171, 31))
        self.label_setting_8.setStyleSheet("font: 8pt \"Arial\";\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 14px;\n"
"line-height: 34px;\n"
"/* identical to box height */\n"
"background: rgba(33, 24, 24, 0.0);\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_setting_8.setObjectName("label_setting_8")
        self.Nickname_1 = QtWidgets.QLineEdit(self.page_setting_1)
        self.Nickname_1.setGeometry(QtCore.QRect(690, 90, 226, 58))
        self.Nickname_1.setStyleSheet("background: rgba(33, 24, 24, 0.7);\n"
"border: 3px solid #575151;\n"
"box-sizing: border-box;\n"
"font: 18pt \"Arial\";\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 8px;\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;")
        self.Nickname_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Nickname_1.setObjectName("Nickname_1")
        self.label_10 = QtWidgets.QLabel(self.page_setting_1)
        self.label_10.setGeometry(QtCore.QRect(770, 10, 121, 31))
        self.label_10.setStyleSheet("background: rgba(33, 24, 24, 0.0);\n"
"font: 16pt \"Arial\";\n"
"box-sizing: border-box;\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"\n"
"font-weight: normal;\n"
"\n"
"line-height: 40px;\n"
"\n"
"color: #FFFFFF;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.next_on_page_2_button = QtWidgets.QPushButton(self.page_setting_1)
        self.next_on_page_2_button.setGeometry(QtCore.QRect(890, 14, 31, 26))
        self.next_on_page_2_button.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.next_on_page_2_button.setText("")
        self.next_on_page_2_button.setIcon(icon10)
        self.next_on_page_2_button.setObjectName("next_on_page_2_button")
        self.button_language_r = QtWidgets.QPushButton(self.page_setting_1)
        self.button_language_r.setGeometry(QtCore.QRect(740, 324, 31, 26))
        self.button_language_r.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_language_r.setText("")
        self.button_language_r.setIcon(icon10)
        self.button_language_r.setObjectName("button_language_r")
        self.button_behavior_r = QtWidgets.QPushButton(self.page_setting_1)
        self.button_behavior_r.setGeometry(QtCore.QRect(740, 390, 31, 26))
        self.button_behavior_r.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_behavior_r.setText("")
        self.button_behavior_r.setIcon(icon10)
        self.button_behavior_r.setObjectName("button_behavior_r")
        self.button_language_l = QtWidgets.QPushButton(self.page_setting_1)
        self.button_language_l.setGeometry(QtCore.QRect(230, 324, 31, 26))
        self.button_language_l.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_language_l.setText("")
        self.button_language_l.setIcon(icon11)
        self.button_language_l.setObjectName("button_language_l")
        self.button_behavior_l = QtWidgets.QPushButton(self.page_setting_1)
        self.button_behavior_l.setGeometry(QtCore.QRect(230, 390, 31, 26))
        self.button_behavior_l.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_behavior_l.setText("")
        self.button_behavior_l.setIcon(icon11)
        self.button_behavior_l.setObjectName("button_behavior_l")
        self.button_character_r = QtWidgets.QPushButton(self.page_setting_1)
        self.button_character_r.setGeometry(QtCore.QRect(640, 130, 31, 26))
        self.button_character_r.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_character_r.setText("")
        self.button_character_r.setIcon(icon10)
        self.button_character_r.setObjectName("button_character_r")
        self.button_character_l = QtWidgets.QPushButton(self.page_setting_1)
        self.button_character_l.setGeometry(QtCore.QRect(450, 130, 31, 26))
        self.button_character_l.setStyleSheet("background: rgba(33, 24, 24, 0.0);")
        self.button_character_l.setText("")
        self.button_character_l.setIcon(icon11)
        self.button_character_l.setObjectName("button_character_l")
        self.stackedWidget_2.addWidget(self.setting_page_1)
        self.stackedWidget.addWidget(self.setting_page)
        self.page_main_min = QtWidgets.QWidget()
        self.page_main_min.setObjectName("page_main_min")
        self.main_min_frame = QtWidgets.QFrame(self.page_main_min)
        self.main_min_frame.setGeometry(QtCore.QRect(490, 230, 481, 281))
        self.main_min_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_min_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_min_frame.setObjectName("main_min_frame")
        self.main_min_button_panel = QtWidgets.QFrame(self.main_min_frame)
        self.main_min_button_panel.setGeometry(QtCore.QRect(30, 60, 350, 111))
        self.main_min_button_panel.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.main_min_button_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_min_button_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_min_button_panel.setObjectName("main_min_button_panel")
        self.character_s_min = QtWidgets.QLabel(self.main_min_button_panel)
        self.character_s_min.setEnabled(True)
        self.character_s_min.setGeometry(QtCore.QRect(240, 10, 92, 90))
        self.character_s_min.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.character_s_min.setText("")
        self.character_s_min.setPixmap(QtGui.QPixmap("material/Neko/Neko_s.png"))
        self.character_s_min.setScaledContents(True)
        self.character_s_min.setObjectName("character_s_min")
        self.area_min_main = QtWidgets.QScrollArea(self.main_min_button_panel)
        self.area_min_main.setGeometry(QtCore.QRect(20, 20, 211, 71))
        self.area_min_main.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.area_min_main.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_min_main.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_min_main.setWidgetResizable(True)
        self.area_min_main.setObjectName("area_min_main")
        self.area_min_main_container = QtWidgets.QWidget()
        self.area_min_main_container.setGeometry(QtCore.QRect(0, 0, 211, 71))
        self.area_min_main_container.setStyleSheet("background: rgba(23, 23, 23, 0.0);")
        self.area_min_main_container.setObjectName("area_min_main_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.area_min_main_container)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_note_min = QtWidgets.QPushButton(self.area_min_main_container)
        self.button_note_min.setEnabled(True)
        self.button_note_min.setMinimumSize(QtCore.QSize(50, 50))
        self.button_note_min.setMaximumSize(QtCore.QSize(50, 50))
        self.button_note_min.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.button_note_min.setText("")
        self.button_note_min.setIcon(icon1)
        self.button_note_min.setIconSize(QtCore.QSize(50, 50))
        self.button_note_min.setAutoDefault(False)
        self.button_note_min.setDefault(False)
        self.button_note_min.setObjectName("button_note_min")
        self.gridLayout_3.addWidget(self.button_note_min, 1, 0, 1, 1)
        self.like_command_button_min = QtWidgets.QPushButton(self.area_min_main_container)
        self.like_command_button_min.setEnabled(True)
        self.like_command_button_min.setMinimumSize(QtCore.QSize(50, 50))
        self.like_command_button_min.setMaximumSize(QtCore.QSize(50, 50))
        self.like_command_button_min.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.like_command_button_min.setText("")
        self.like_command_button_min.setIcon(icon2)
        self.like_command_button_min.setIconSize(QtCore.QSize(50, 50))
        self.like_command_button_min.setAutoDefault(False)
        self.like_command_button_min.setDefault(False)
        self.like_command_button_min.setObjectName("like_command_button_min")
        self.gridLayout_3.addWidget(self.like_command_button_min, 1, 1, 1, 1)
        self.teg_button_min = QtWidgets.QPushButton(self.area_min_main_container)
        self.teg_button_min.setEnabled(True)
        self.teg_button_min.setMinimumSize(QtCore.QSize(50, 50))
        self.teg_button_min.setMaximumSize(QtCore.QSize(50, 50))
        self.teg_button_min.setStyleSheet("background: rgba(23, 23, 23, 0.0);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;")
        self.teg_button_min.setText("")
        self.teg_button_min.setIcon(icon)
        self.teg_button_min.setIconSize(QtCore.QSize(50, 50))
        self.teg_button_min.setAutoDefault(False)
        self.teg_button_min.setDefault(False)
        self.teg_button_min.setObjectName("teg_button_min")
        self.gridLayout_3.addWidget(self.teg_button_min, 1, 2, 1, 1)
        self.area_min_main.setWidget(self.area_min_main_container)
        self.wrap_button = QtWidgets.QPushButton(self.main_min_frame)
        self.wrap_button.setGeometry(QtCore.QRect(30, 180, 344, 41))
        self.wrap_button.setStyleSheet("background: rgba(23, 23, 23, 0.9);\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-size: 18px;\n"
"line-height: 27px;\n"
"\n"
"color: #FFFFFF;")
        self.wrap_button.setObjectName("wrap_button")
        self.label_dialog_min_frame = QtWidgets.QLabel(self.main_min_frame)
        self.label_dialog_min_frame.setGeometry(QtCore.QRect(390, 70, 83, 73))
        self.label_dialog_min_frame.setStyleSheet("background: #2B2525;\n"
"border: 2px solid #A7A7A7;\n"
"\n"
"box-shadow: 2px 4px 4px rgba(0, 0, 0, 0.25);\n"
"border-radius: 13px;\n"
"font-family: Titillium Web;\n"
"font-style: normal;\n"
"font-weight: normal;\n"
"font-size: 12px;\n"
"line-height: 27px;\n"
"text-align: center;\n"
"padding: 0 0 0 13px;\n"
"color: #FFFFFF;")
        self.label_dialog_min_frame.setObjectName("label_dialog_min_frame")
        self.stackedWidget.addWidget(self.page_main_min)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stacked_add_frame.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dialog_character.setText(_translate("MainWindow", "Семпай, надеюсь, ты меня не просто так позвал?"))
        self.setting_button.setText(_translate("MainWindow", "setting"))
        self.rule_button.setText(_translate("MainWindow", "ruling command"))
        self.q_a_button.setText(_translate("MainWindow", "q&&a"))
        self.lineedit_command.setText(_translate("MainWindow", "enter name command..."))
        self.label_add_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Фиро: позволь помочь тебе с составлением команд</span></p></body></html>"))
        self.label_add_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Фиро: так можно указать сайт!</span></p></body></html>"))
        self.save_command_button.setText(_translate("MainWindow", "save"))
        self.label_add_click_1.setText(_translate("MainWindow", "*клик*"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_add_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">...</span></p></body></html>"))
        self.lineedit_site.setText(_translate("MainWindow", "set site"))
        self.label_add_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">команде название.</span></p></body></html>"))
        self.label_add_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Фиро: так можно выбрать файлы </span></p></body></html>"))
        self.label_add_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Фиро: выбери что-то одно, затем укажи </span></p></body></html>"))
        self.label_add_click_3.setText(_translate("MainWindow", "*клик*"))
        self.back_from_add_button.setText(_translate("MainWindow", "back"))
        self.label_add_click_2.setText(_translate("MainWindow", "*клик*"))
        self.label_add_click_4.setText(_translate("MainWindow", "*клик*"))
        self.label_add_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12px;\">Фиро выполнит ваше поручение!</span></p></body></html>"))
        self.label_add_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">или приложения!</span></p></body></html>"))
        self.delite_button.setText(_translate("MainWindow", "delite"))
        self.label_about_delite.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12px;\">кликни на те,которые хочешь удалить</span></p></body></html>"))
        self.label_info_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Если хочешь быстрый доступ к сайту то вставь ссылку</span></p></body></html>"))
        self.label_add_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Если хочешь добавить приложение в быстрый запуск то *кликни* на хлеб</span></p></body></html>"))
        self.label_info_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Titillium Web\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Полагаю, у тебя есть приложения, которыми ты почти не пользуешься, но *вдруг понадобятся*, предлагаю хранить их под рукой</span></p></body></html>"))
        self.label_setting_page_2.setText(_translate("MainWindow", "setting"))
        self.label_window_page_2.setText(_translate("MainWindow", "main window"))
        self.label_normal_window_page_2.setText(_translate("MainWindow", "Normal size"))
        self.label_page_2.setText(_translate("MainWindow", "page 2"))
        self.label_setting.setText(_translate("MainWindow", "setting"))
        self.label_setting_1.setText(_translate("MainWindow", "Вайфу это твой выбор"))
        self.label_setting_4.setText(_translate("MainWindow", "язык"))
        self.label_setting_5.setText(_translate("MainWindow", "характер"))
        self.label_setting_2.setText(_translate("MainWindow", "Укажите  свой  ник"))
        self.Nickname_2.setText(_translate("MainWindow", "нике"))
        self.label_setting_6.setText(_translate("MainWindow", "русский"))
        self.label_setting_7.setText(_translate("MainWindow", "вайфу"))
        self.button_save.setText(_translate("MainWindow", "save"))
        self.back_fome_setting_button.setText(_translate("MainWindow", "back"))
        self.label_setting_8.setText(_translate("MainWindow", "Укажите  ник  персонажа"))
        self.Nickname_1.setText(_translate("MainWindow", "нике"))
        self.label_10.setText(_translate("MainWindow", "page 1"))
        self.wrap_button.setText(_translate("MainWindow", "wrap"))
        self.label_dialog_min_frame.setText(_translate("MainWindow", "Рада вас\n"
" видеть\n"
" хозяин"))

